#!/usr/bin/env bash
# Detects if the current WM is i3, Sway, or SwayFX. This output is then used by the i3 configuration file to source necessary configurations for each environment. 
if [[ $XDG_CURRENT_DESKTOP == 'sway' ]] || [[ $XDG_SESSION_DESKTOP == 'sway' ]] || [[ $DESKTOP_SESSION == 'sway' ]]; then
	# Check if first word of sway version is swayfx or not
	if [[ $(sway --version | awk '{print $1}') == "swayfx" ]]; then
		i3type='swayfx'
	elif [[ $(sway --version | awk '{print $1}') == "sway" ]]; then
		i3type='sway'
	fi
elif [[ $XDG_CURRENT_DESKTOP == 'i3' ]] || [[ $XDG_SESSION_DESKTOP == 'i3' ]] || [[ $DESKTOP_SESSION == 'i3' ]] && [[ $(i3 --version) =~ "^i3 " ]]; then
	i3type='i3'
else
	# Fall back to standard i3
	# I may make something here that spits an error to the screen if no i3type is detected, possibly using zenity and/or i3-nagbar
	i3type='none'
fi
export i3type
echo i3-like environment is $i3type
