#!/usr/bin/env bash

# Check if this is a Sway or SwayFX session
sourceife $HOME/.config/sway/scripts/swayfxdetect

if [[ $1 == 'x11' ]]; then
	# If we're on X11, overwrite the i3type from a Sway one to i3.
	sourceife $HOME/.config/i3/scripts/swaydetect

	# Set display preset
	runife $HOME/.screenlayout/$(hostname).sh


	# Display backlight managment
	#clight-gui --tray &

	# Display configuration
	#autorandr --change	# Handled by autorandr.service
	
	# WM-independent keybinds
	#xbindkeys

	# KDE Connect
	/usr/lib/kdeconnectd &

	# Use GUI polkit authentication
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


	# Bar services
	#$HOME/.local/bin/mowbatcheck &
	## Disable mpvradio on login
	$HOME/.config/polybar/scripts/mpvradio rclick &

	# Theme Fixes
	#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
	xrdb ~/.Xresources

	# Fallback to manually set dvorak keyboard layout in X11
	#setxkbmap -layout us,us -variant 'dvorak, '
	
	# Tray applets
	snixembed & # Fix Equibop
	blueman-applet &
	ibus-daemon &
	kdeconnect-indicator &
	nm-applet &
	xfce4-clipman &
fi

thunar --daemon &

# UxPlay background service
# TODO: Make an actual service
#stdbuf -o0 uxplay -p -pw | grep --line-buffered PIN | xargs -I {} notify-send "{}"
