#!/usr/bin/env bash
showstartscounter='false' # Setting this to false still counts startups but does not display the message
startscounterfile="$HOME/.local/share/shell/startscounter"

[ ! -f $startscounterfile ] && echo '0' > "$startscounterfile" && echo 'Shell startup counter file created'
# TODO: Find a way to increment and set $startscounter in one expression
startscounter=$(cat $startscounterfile)
((startscounter++))
echo $startscounter > $startscounterfile 

if [[ "$showstartscounter" == 'true' ]]; then
	echo "You have opened your shell $startscounter times"
fi
