#!/usr/bin/env bash
export PATH=$PATH:"$HOME/.local/bin"

export EDITOR='/usr/bin/nvim'
export VISUAL=$EDITOR 
export PAGER='nvimpager'
export MANPAGER='nvim +Man!'

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=100000
setopt autocd correct histignorespace PROMPT_SUBST
unsetopt beep
bindkey -e
