#!/usr/bin/env bash

# Nord
# https://www.nordtheme.com/docs/colors-and-palettes
export nord0="#2e3440"
export nord1="#3b4252"
export nord2="#434c5e"
export nord3="#4c566a"

export nord4="#d8dee9"
export nord5="#e5e9f0"
export nord6="#eceff4"

export nord7="#8fbcbb"
export nord8="#88c0d0"
export nord9="#81a1c1"
export nord10="#5e81ac"

export nord11="#bf616a"
export nord12="#d08770"
export nord13="#ebcb8b"
export nord14="#a3be8c"
export nord15="#b48ead"

# Transparency Configurations
# TODO: Make this automatically use the defaults if the variable is not set instead of requiring manual definitions
util_hex_trans='230' # Transparency for hex colors
util_pct_trans='90' # Percentage-based transparency
util_dec_trans='90' # Decimal-based transparency
util_bg_hex_trans="$util_hex_trans"
util_bg_pct_trans="$util_pct_trans"
util_bg_dec_trans="$util_dec_trans"
util_bg_raised_hex_trans="$util_hex_trans"
util_bg_raised_pct_trans="$util_pct_trans"
util_bg_raised_dec_trans="$util_dec_trans"
util_primary_hex_trans="$util_hex_trans"
util_primary_pct_trans="$util_pct_trans"
util_primary_dec_trans="$util_dec_trans"
util_bg_highest_hex_trans="$util_hex_trans"
util_bg_highest_pct_trans="$util_pct_trans"
util_bg_highest_dec_trans="$util_dec_trans"

# Final theme configuration
export theme_bg="$nord0"
export theme_bg_raised="$nord1"
export theme_bg_highlight="$nord2"
export theme_bg_highest="$nord3"
export theme_txt="$nord4"
export theme_txt_brighter="$nord5"
export theme_txt_brightest="$nord6"
export theme_primary="$nord10"
export theme_error="$nord11"
export theme_danger="$nord12"
export theme_warn="$nord13"
export theme_success="$nord14"

export theme_bg_pct_trans="$theme_bg$util_bg_pct_trans"
export theme_bg_raised_pct_trans="$theme_bg_raised$util_bg_raised_pct_trans"
export theme_bg_highlight_pct_trans="$theme_bg_highlight$util_primary_pct_trans"
export theme_bg_highest_pct_trans="$theme_bg_highest$util_bg_highest_pct_trans"
