#!/usr/bin/env bash

# Nord
# https://www.nordtheme.com/docs/colors-and-palettes
export nord0="#2e3440"
export nord1="#3b4252"
export nord2="#434c5e"
export nord3="#4c566a"

export nord4="#d8dee9"
export nord5="#e5e9f0"
export nord6="#eceff4"

export nord7="#8fbcbb"
export nord8="#88c0d0"
export nord9="#81a1c1"
export nord10="#5e81ac"

export nord11="#bf616a"
export nord12="#d08770"
export nord13="#ebcb8b"
export nord14="#a3be8c"
export nord15="#b48ead"

# Final theme configuration
export theme_bg="$nord0"
export theme_bg_raised="$nord1"
export theme_bg_highlight="$nord2"
export theme_bg_highest="$nord3"
export theme_text="$nord4"
export theme_txt_brighter="$nord5"
export theme_txt_brightest="$nord6"
export theme_primary="$nord10"
export theme_error="$nord11"
export theme_success="$nord14"
