#!/usr/bin/env bash

# XDG Base Directory Specification
export PATH=$PATH:"$HOME/.local/bin"
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# Home cleanup ----------------------------------
## ~/.android
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
## ~/.cargo
export CARGO_HOME="$XDG_DATA_HOME"/cargo
## ~/.gnupg
#export GNUPGHOME="$XDG_DATA_HOME"/gnupg
## ~/.gradle
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
## ~/.gtkrc-2.0
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
## ~/.icons
export XCURSOR_PATH=/usr/share/icons:$XDG_DATA_HOME/icons
## ~/.dvdcss
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
## ~/.nimble
export NIMBLE_DIR="$XDG_DATA_HOME/nimble"
## ~/.npm
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME"/npm/config/npm-init.js
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR"/npm
## ~/.nvm
export NVM_DIR="$XDG_DATA_HOME"/nvm
## ~/.java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
## ~/.parallel
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
## ~/.rustup
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
## ~/.wine
export WINEPREFIX="$XDG_DATA_HOME"/wine
## ~/.xsession-errors
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

