#!/usr/bin/env bash
# Define functions and other things necessary before the rest of the shell startup scripts are run

# Automatically start the X server if this is TTY1
if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ] && [ "$isxprofile" != 1]; then
  exec startx
fi

# Source if file exists
function sourceife () {
	if [ -f "$1" ]; then
		source "$@"
	fi
}

# Run if file exist
function runife () {
	if [ -f "$1" ]; then
		"$@"
	fi
}

# Run if command exists
function runifce () {
	if [ -f "$(which $1)" ]; then
		"$@"
	fi
}

# Set environment variables
sourceife $HOME/.config/shell/environment
