[module/xworkspaces]
type = internal/xworkspaces

; Functionality/Interaction
enable-click = true
enable-scroll = false
reverse-scroll = true
#pin-workspaces = true
# Ends up using a weird order on i3 that doesn't match the monitor configuration *or* i3 workspace order
#group-by-monitor = false

; Labels and looks
label-active = %icon%
label-active-background = ${colors.background-alt}
;label-active-overline= ${colors.primary}
label-active-underline= ${colors.primary}
label-active-padding = 3

label-occupied = %icon%
label-occupied-padding = 3

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 3

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 3

; Icons
;icon-0 = 1;
icon-0 =  1;
icon-1 =  2;󰖟
icon-2 =  3;󰲤
icon-3 =  4;󰲦
icon-4 =  5;
icon-5 =  6;󰊗
icon-6 =  7;󰲬
icon-7 =  8;󰍩
icon-8 =  9;󰐍
icon-9 =  10;󰿬
icon-10 = bg;
icon-default = 
