#!/usr/bin/env zsh
autoload -Uz promptinit
promptinit
fpath=("$HOME/.config/zsh/prompts" "$fpath[@]")

function loadpromptvars () {
	# Glyphs and Icons
	ledge='' # Left edge character (start of PS1)
	redge='' # Right edge character (end of RPROMPT)
	lsep1='' # Separator between sections
	lsep2='' # Separator between sections
	#lsepalt='' # Thin separator indicating a hidden section
	rsep1='' # Separator between sections
	rsep2='' # Separator between sections
	#rsepalt='' # Thin separator indicating a hidden section
	lend="$lsep2" # Right end of $PS1
	rend="$rsep2" # Left end of RPROMPT

	# Colors
	if [[ "$COLORTERM" == 'truecolor' ]]; then
		txt="$theme_txt"
		ltxt="$theme_txt"
		rtxt="$theme_bg"
		lc1="$theme_positive" # Left colors
		lc2="$theme_positive"
		rc1="$theme_primary" # Right colors
		rc2="$theme_primary"
		rc3="$theme_primary"
	else
		txt="15" # Text color
		lc1="27" # Left colors
		lc2="39"
		rc1="207" # Right colors
		rc2="201"
		rc3="165"
	fi

	txtc="%F{$txt}" # Text color
	ltxtc="%F{$ltxt}"
	rtxtc="%F{$rtxt}"
	lfg1="%F{$lc1}" # Left foreground colors
	lfg2="%F{$lc2}"
	rfg1="%F{$rc1}" # Right foreground colors
	rfg2="%F{$rc2}"
	rfg3="%F{$rc3}"

	lbg1="%K{$lc1}" # Left background colors
	lbg2="%K{$lc2}"
	rbg1="%K{$rc1}" # Right background colors
	rbg2="%K{$rc2}"
	rbg3="%K{$rc3}"

	# Reset Colors
	resetfg='%f'
	resetbg='%k'
	resetc='%f%k'
}

function clearpromptvars () {
	unset txt lc1 lc2 rc1 rc2 rc3 lfg1 lfg2 rfg1 rfg2 rfg3 lbg1 lbg2 rbg1 rbg2 rbg3 resetfg resetbg resetc
}

function cleanecp () {
	ecpout="$(ecp $@)"
	# If the error code is missing or 0 (ok), then don't show anything
	if [[ $ecpout != '0 (ok)' ]] || [[ -z $ecpout ]]; then
		loadpromptvars
		echo -n "$rbg1$rtxtc $ecpout "
		clearpromptvars
	else
		echo -n ""
	fi	
}
function cleanpwd () {
	dir="$(print -rD $PWD)"
	# If in the home folder, then don't show anything
	if [[ $dir != '~' ]]; then
		loadpromptvars
		echo -n "$lbg2$txtc $dir "
		clearpromptvars
	else
		echo -n ""
	fi
}

prompt_slick-arrows_setup () {
	# TODO: Improve performance
	loadpromptvars

	PS1="$lfg1$ledge$lbg1$ltxtc"' %n '"$resetc$lfg1$lsep2$lfg2$lsep1$ltxtc"'$(cleanpwd)'"$resetc$lfg2$lsep2$resetc "
	RPROMPT="$resetc$rfg1$rsep2$rtxtc"'$(cleanecp $?)'"$resetc$rfg1$rsep1$resetc$rfg2$rsep2$resetc$rbg2$rtxtc $($HOME/.config/shell/detectbox) $resetc$rfg2$rsep1$resetc$rfg3$rsep2$rbg3$rtxtc"' %* '"$resetbg$rfg3$redge$resetc"

	clearpromptvars
}

# Done
prompt_themes+=( slick-arrows )

