#!/usr/bin/env zsh
autoload -Uz promptinit
promptinit
fpath=("$HOME/.config/zsh/prompts" "$fpath[@]")

# Glyphs and Icons
ledge='' # Left edge character (start of PS1)
redge='' # Right edge character (end of RPROMPT)
lsep1='' # Separator between sections
lsep2='' # Separator between sections
#lsepalt='' # Thin separator indicating a hidden section
rsep1='' # Separator between sections
rsep2='' # Separator between sections
#rsepalt='' # Thin separator indicating a hidden section
lend="$lsep" # Right end of $PS1
rend="$rsep" # Left end of RPROMPT

# Colors
txt="15" # Text color
lc1="27" # Left colors
lc2="39"
rc1="207" # Right colors
rc2="201"
rc3="165"

txtc="%F{$txt}" # Text color
lfg1="%F{$lc1}" # Left foreground colors
lfg2="%F{$lc2}"
rfg1="%F{$rc1}" # Right foreground colors
rfg2="%F{$rc2}"
rfg3="%F{$rc3}"

lbg1="%K{$lc1}" # Left background colors
lbg2="%K{$lc2}"
rbg1="%K{$rc1}" # Right background colors
rbg2="%K{$rc2}"
rbg3="%K{$rc3}"

# Reset Colors
resetfg='%f'
resetbg='%k'
resetc='%f%k'

function cleanecp () {
	ecpout=$(ecp $@)
	# If the error code is missing or 0 (ok), then don't show anything
	if [[ $ecpout != '0 (ok)' ]] || [[ -z $ecpout ]]; then
		#ecp $@
		echo -n "$rbg1$txtc $ecpout "
	else
		echo -n ""
	fi	
}
function cleanpwd () {
	dir=$(print -rD $PWD)
	if [[ $dir != '~' ]]; then
		echo -n "$lbg2$txtc $dir "
	else
		echo -n ""
	fi
}

prompt_slick-arrows_setup () {
	PS1="$lfg1$ledge$lbg1$txtc"' %n '"$resetc$lfg1$lsep2$lfg2$lsep1$txtc"'$(cleanpwd)'"$resetc$lfg2$lsep2$resetc "
	RPROMPT="$rfg1$rsep2"'$(cleanecp $?)'"$resetc$rfg1$rsep1$resetc$rfg2$rsep2$resetc$rbg2$txtc $($HOME/.config/shell/detectbox) $resetc$rfg2$rsep1$resetc$rfg3$rsep2$rbg3$txtc"' %* '"$resetbg$rfg3$redge$resetc"
}
prompt_themes+=( slick-arrows )

# Find a way to safely unset these without breaking the prompt
#unset txt lc1 lc2 rc1 rc2 rc3 lfg1 lfg2 rfg1 rfg2 rfg3 lbg1 lbg2 rbg1 rbg2 rbg3 resetfg resetbg resetc
