#!/usr/bin/env bash
# Inspired by https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/updates-pacman-aurhelper

# Check if running on Arch Linux. Exit if not or unkown.
if [ -f '/etc/os-release' ]; then
	source '/etc/os-release'
	if ! [[ $ID = 'arch' ]]; then
		exit
	fi
else
	exit
fi

aurhelperlist=("paru" "yay")
parucmd='paru -Qum'
yaycmd='yay -Qum'
pikaurcmd='pikaur -Qua'

# Loading string
echo "$(echo %{F$theme_primary}󰚰%{F-} )"
updatecount=$((paru -Qum 2> /dev/null & checkupdates 2> /dev/null) | wc -l)
if [[ $updatecount > 0 ]]; then
	outline="$(echo %{F$theme_primary}󰚰%{F-} $updatecount)"
fi
# The bar item will be empty if there are no updates ($outline variable not set), which will save space
echo $outline
sleep 600
