#!/usr/bin/env bash
# Inspired by https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/updates-pacman-aurhelper

# Check if running on Arch Linux. Exit if not or unkown.
if [ -f '/etc/os-release' ]; then
	source '/etc/os-release'
	if ! [[ $ID = 'arch' ]]; then
		exit
	fi
else
	exit
fi

minupdatecount=50

aurhelperlist=('paru' 'yay' 'pikaur')
parucmd='paru -Qum'
yaycmd='yay -Qum'
pikaurcmd='pikaur -Qua'

# https://unix.stackexchange.com/a/190610 
# Check network status
function net () {
	if nc -zw1 archlinux.org 443 2>/dev/null && echo | openssl s_client -connect archlinux.org:443 2>&1 | awk '
		$1 == "SSL" && $2 == "handshake" { handshake = 1 }
		handshake && $1 == "Verification:" { ok = $2; exit }
		END { exit ok != "OK" }'; then
		true
	else
		false
	fi
}
while ! net; do
	net
	sleep 120
done

# Loading string
echo "$(echo %{F$theme_primary}󰚰%{F-} )"

# TODO: Set up checking for specific upgrades, such as `linux`, `firefox`, and other important packages. 
updatecount=$( ( paru -Qum 2>/dev/null & checkupdates 2>/dev/null & \
	( flatpak remote-ls --updates --all | tail -n +1 ) & \
	( rustup --quiet check | head -n -1 | grep 'Update available' ) \
	) | wc -l )
if [ $updatecount -ge $minupdatecount ]; then
	outline="$(echo %{F$theme_primary}󰚰%{F-} $updatecount)"
fi
# The bar item will be empty if there are no updates ($outline variable not set), which will save space
echo $outline
sleep 300
