#!/usr/bin/env bash
if command -v mxw &>/dev/null; then
	bat=$(mxw report battery --hide-status 2>/dev/null)
elif command -v mow &>/dev/null; then
	bat=$(mow report battery 2>/dev/null)
else
	echo 'No Glorious wireless mouse support tool (mxw, mow) installed'
	exit 2
fi


if [[ "$bat" = *\%* ]]; then
	#set -- $bat
	#echo $1
	echo -n " $bat"
else
	exit 1
fi

